Resposta da atividade 3-5
/////////////////////////////

CREATE TABLE `DEPARTAMENTO` (
    `CODIGO`          INT(11)      NOT NULL,
    `NOME`            VARCHAR(100) NOT NULL,
    PRIMARY KEY (`CODIGO`),
    UNIQUE KEY `CODIGO` (`CODIGO`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `FUNCIONARIO` (
    `MATRICULA`       INT(11)      NOT NULL,
    `NOME`            VARCHAR(100) NOT NULL,
    `SALARIO`         DECIMAL(10,2) NOT NULL,
    `GERENTE`         INT(11)      DEFAULT NULL,
    `DEPARTAMENTO`    INT(11)      NOT NULL,
    PRIMARY KEY (`MATRICULA`),
    UNIQUE KEY `MATRICULA` (`MATRICULA`) USING HASH,
    KEY `DEPARTAMENTO` (`DEPARTAMENTO`) USING BTREE,
    KEY `FUNCIONARIO_FK_1` (`GERENTE`),
    CONSTRAINT `FUNCIONARIO_FK` FOREIGN KEY (`DEPARTAMENTO`) REFERENCES `DEPARTAMENTO` (`CODIGO`),
    CONSTRAINT `FUNCIONARIO_FK_1` FOREIGN KEY (`GERENTE`) REFERENCES `FUNCIONARIO` (`MATRICULA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
